// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/llm/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/llm/client.go -destination=./internal/llm/mock_client.go -package=llm
//

// Package llm is a generated GoMock package.
package llm

import (
	models "myapp/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetCompletion mocks base method.
func (m *MockClient) GetCompletion(message string, messages []models.ChatMessage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletion", message, messages)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletion indicates an expected call of GetCompletion.
func (mr *MockClientMockRecorder) GetCompletion(message, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletion", reflect.TypeOf((*MockClient)(nil).GetCompletion), message, messages)
}
